### ISSUE TITLE
Hud Didnt Disappear

### ISSUE THREAD

**Issue by ImToggle** [Tellinq/Potion-Effects#11]
i got effect in a server and then quit it, but it still shows the potion hud, and the timer is paused

version: latest commit

https://youtu.be/hGTOCdKkSE4

**Comment by Tellinq** [comment]
Hey there! Can you try the latest GitHub actions to see if your issue is resolved?

**Comment by ImToggle** [comment]
yes, its fixed

**Comment by Tellinq** [comment]
Sweet
