### ISSUE TITLE
The effects doesn't get removed after world update

### ISSUE THREAD

**Issue by JustInfLOL** [Tellinq/Potion-Effects#12]
For example, if I joined a world with effects(e.g hypixel lobby), then join a world without any potion effects like duels or waiting lobby of games, the previous effect doesnt get cleared until new effects in the new world appear.

**Comment by Tellinq** [comment]
Hey there! Can you try the latest GitHub actions to see if your issue is resolved?

**Comment by Tellinq** [comment]
#11 I believe is the same issue, which also says that their issue is resolved. Please let me know if the issue is also fixed for you.
